name: Quick Deploy Frontend Only

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.env.production'
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'

jobs:
  deploy-frontend-fast:
    runs-on: ubuntu-latest
    name: Quick Frontend Deploy

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      run: |
        cd frontend
        npm ci

    - name: Build frontend
      run: |
        cd frontend
        # Uses .env.production for API URL configuration
        npx vite build
      env:
        # Use HTTPS Cloudflare Tunnel URL
        VITE_API_URL: ${{ secrets.VITE_API_URL || 'https://warren-really-interactive-launched.trycloudflare.com' }}

    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "/frontend/dist"
        skip_app_build: true

    - name: Deployment info
      run: |
        echo "✅ Frontend deployed to Azure Static Web Apps"
        echo "📝 Backend: See CLOUDFLARE_SETUP.md for HTTPS configuration"

