name: Deploy Backend to Azure

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - 'requirements.txt'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: kg-backend-app-free
  PYTHON_VERSION: '3.9'
  AZURE_RESOURCE_GROUP: kg-free-rg

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Resource Group
      run: |
        az group create --name ${{ env.AZURE_RESOURCE_GROUP }} --location eastus

    - name: Create App Service Plan
      run: |
        if ! az appservice plan show --name kg-backend-plan --resource-group ${{ env.AZURE_RESOURCE_GROUP }} &> /dev/null; then
          az appservice plan create \
            --name kg-backend-plan \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --sku B1 \
            --is-linux
        fi

    - name: Create Web App
      run: |
        if ! az webapp show --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} &> /dev/null; then
          az webapp create \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --plan kg-backend-plan \
            --runtime "PYTHON|3.9"
        fi

    - name: Configure Web App Settings
      run: |
        az webapp config appsettings set \
          --name ${{ env.AZURE_WEBAPP_NAME }} \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --settings \
            OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
            SCM_DO_BUILD_DURING_DEPLOYMENT=true \
            ENABLE_ORYX_BUILD=true

    - name: Configure Startup Command
      run: |
        az webapp config set \
          --name ${{ env.AZURE_WEBAPP_NAME }} \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --startup-file "uvicorn server:app --host 0.0.0.0 --port 8000"

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: .

    - name: Azure Logout
      run: |
        az logout
      if: always()

