name: Student Frontend Deploy

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/student-frontend-deploy.yml'
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    name: Deploy Frontend to Student Static Web App

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: |
          cd frontend
          npm ci --legacy-peer-deps

      - name: Build frontend
        run: |
          cd frontend
          npm run build
        env:
          VITE_API_URL: ${{ secrets.STUDENT_BACKEND_URL }}

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STUDENT_STATIC_WEB_APPS_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/frontend/dist"
          skip_app_build: true

      - name: Deployment summary
        run: |
          echo "✅ Student Frontend deployed successfully!"
          echo "📝 Frontend will be available at the Static Web App URL"
