name: Student Backend Deploy

on:
  push:
    branches: [main]
    paths:
      - '**.py'
      - 'Dockerfile'
      - 'requirements.txt'
      - 'personas/**'
      - 'data/**'
      - '.github/workflows/student-backend-deploy.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: kg-backend
  RESOURCE_GROUP: kg-student-20251031184510-rg
  CONTAINER_APP: kg-student-backend
  CONTAINER_ENV: kg-student-env
  LOCATION: eastus2

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_STUDENT_CREDENTIALS }}

      - name: Update Container App
        run: |
          az containerapp update \
            --name ${{ env.CONTAINER_APP }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest \
            --set-env-vars "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"

      - name: Get Container App URL
        id: get-url
        run: |
          FQDN=$(az containerapp show \
            --name ${{ env.CONTAINER_APP }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --query properties.configuration.ingress.fqdn -o tsv)

          echo "Backend FQDN: $FQDN"
          echo "backend_url=https://$FQDN" >> $GITHUB_OUTPUT
          echo "🚀 Backend deployed at https://$FQDN"

      - name: Verify deployment
        run: |
          BACKEND_URL="${{ steps.get-url.outputs.backend_url }}"

          echo "Waiting for Container App to be ready..."
          sleep 15

          # Test health endpoint with HTTPS
          if curl -sf "$BACKEND_URL/" > /dev/null 2>&1; then
            echo "✅ Backend is healthy!"
            curl -s "$BACKEND_URL/" | jq .
          else
            echo "⚠️  Backend might not be ready yet. Check logs manually."
          fi

      - name: Azure Logout
        run: az logout
        if: always()
